/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.ui;

import com.poly.dao.TaiKhoanDAO;
import com.poly.entity.TaiKhoan;
import com.poly.utils.Auth;
import com.poly.utils.MsgBox;
import java.awt.Desktop;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author admin
 */
public class DangNhapJDialog_start extends javax.swing.JDialog {

    /**
     * Creates new form DangNhapJdialog
     */
    public DangNhapJDialog_start(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTenDangNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btnDangNhap = new javax.swing.JButton();
        thoat = new javax.swing.JLabel();
        lblQuenMK = new javax.swing.JLabel();
        lblFB = new javax.swing.JLabel();
        lblTW = new javax.swing.JLabel();
        lblPT = new javax.swing.JLabel();
        lblYT = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 113, 177));
        jLabel1.setText("Tên Đăng Nhập: ");

        txtTenDangNhap.setBackground(new java.awt.Color(32, 33, 35));
        txtTenDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        txtTenDangNhap.setText("TeoNV");
        txtTenDangNhap.setBorder(null);
        txtTenDangNhap.setCaretColor(new java.awt.Color(255, 255, 255));
        txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDangNhapActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 113, 177));
        jLabel2.setText("Mật Khẩu: ");

        txtMatKhau.setBackground(new java.awt.Color(32, 33, 35));
        txtMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        txtMatKhau.setText("123");
        txtMatKhau.setBorder(null);

        btnDangNhap.setBackground(new java.awt.Color(102, 255, 204));
        btnDangNhap.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        btnDangNhap.setText("Sing In");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        thoat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        thoat.setForeground(new java.awt.Color(57, 113, 177));
        thoat.setText("X");
        thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thoatMouseClicked(evt);
            }
        });

        lblQuenMK.setForeground(new java.awt.Color(57, 113, 177));
        lblQuenMK.setText("Fogot Password?");
        lblQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseClicked(evt);
            }
        });

        lblFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/fb.PNG"))); // NOI18N
        lblFB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFBMouseClicked(evt);
            }
        });

        lblTW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/tw.PNG"))); // NOI18N
        lblTW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTWMouseClicked(evt);
            }
        });

        lblPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/p.PNG"))); // NOI18N
        lblPT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPTMouseClicked(evt);
            }
        });

        lblYT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/yu.PNG"))); // NOI18N
        lblYT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lblQuenMK, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblFB)
                                .addGap(18, 18, 18)
                                .addComponent(lblTW)
                                .addGap(18, 18, 18)
                                .addComponent(lblPT)
                                .addGap(18, 18, 18)
                                .addComponent(lblYT)))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thoat)
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblQuenMK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblYT)
                                    .addGap(1, 1, 1))
                                .addComponent(lblTW, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblFB))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPT)
                        .addGap(2, 2, 2)))
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 340, 440));

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/student.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/img/chu.PNG"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thoatMouseClicked
        if (MsgBox.confirm(this, "Bạn có muốn kết thúc ứng dụng")) {
            System.exit(0);
        }
    }//GEN-LAST:event_thoatMouseClicked

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        this.dangnhap();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhapActionPerformed

    private void lblFBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFBMouseClicked
        theodoiFB();
    }//GEN-LAST:event_lblFBMouseClicked

    private void lblTWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTWMouseClicked
        theodoiTW();
    }//GEN-LAST:event_lblTWMouseClicked

    private void lblPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPTMouseClicked
        theodoiPT();
    }//GEN-LAST:event_lblPTMouseClicked

    private void lblYTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYTMouseClicked
        theodoiYT();
    }//GEN-LAST:event_lblYTMouseClicked

    private void lblQuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseClicked
        String t = JOptionPane.showInputDialog("Nhập Email cua ban");
        if (t.equals("")) {
            JOptionPane.showMessageDialog(this, "Ban Can Nhap Email de kich hoat lai mat khau");
        } else {
            Connection conn = null;
            Statement st = null;
            try {
                System.out.println("Connecting to database...");
                conn = DriverManager.getConnection("jdbc:sqlserver://localhost;DatabaseName=QLSV", "sa", "songlong");
                st = conn.createStatement();
                String sql = "select * from TaiKhoan";
                ResultSet rs = st.executeQuery(sql);
                String email;
                boolean flag = false;
                while (rs.next()) {
                    email = rs.getString("Email");
                    if (t.equals(email)) {
//                        guiEmail(t);
                        flag = true;
                        guiEmail(t);
                    }
                }
                if (!flag) {
                    JOptionPane.showMessageDialog(this, "Email khong ton tai");
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lblQuenMKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog_start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog_start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog_start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog_start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapJDialog_start dialog = new DangNhapJDialog_start(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFB;
    private javax.swing.JLabel lblPT;
    private javax.swing.JLabel lblQuenMK;
    private javax.swing.JLabel lblTW;
    private javax.swing.JLabel lblYT;
    private javax.swing.JLabel thoat;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        ChaoJDialog openthis = new ChaoJDialog(frame,true);
        openthis.setLocationRelativeTo(null);
        openthis.setVisible(true);
    }

    TaiKhoanDAO dao = new TaiKhoanDAO();

//    void dangNhap() {
//        String tendangnhap = txtTenDangNhap.getText();
//        String matKhau = new String(txtMatKhau.getPassword());
//        TaiKhoan taiKhoan = dao.selectById(tendangnhap);
//        if (taiKhoan == null) {
//            MsgBox.alert(this, "Sai tên đăng nhập!");
//        } else if (!matKhau.equals(taiKhoan.getMatKhau())) {
//            MsgBox.alert(this, "Sai mật khẩu!");
//        } else {
//            MsgBox.alert(this, "Đăng nhập thành công");
//            this.dispose();
//        }
//    }

    void theodoiFB() {
        try {
            Desktop.getDesktop().browse(new URL("https://www.facebook.com/FPTU.HCM").toURI());
        } catch (Exception e) {
        }
    }
    
    void theodoiTW() {
        try {
            Desktop.getDesktop().browse(new URL("https://twitter.com/elonmusk").toURI());
        } catch (Exception e) {
        }
    }
    
    void theodoiPT() {
        try {
            Desktop.getDesktop().browse(new URL("https://www.pinterest.com/").toURI());
        } catch (Exception e) {
        }
    }
    
    void theodoiYT() {
        try {
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/channel/UCfy8SwDv63yrz6MCJ9CIkNA").toURI());
        } catch (Exception e) {
        }
    }
    
    String url = "jdbc:sqlserver://localhost;DatabaseName=QLSV;user=sa; password=songlong";
    private void guiEmail(String t) throws HeadlessException {
        try {
            Properties p = new Properties();
            p.put("mail.smtp.auth", "true");
            p.put("mail.smtp.starttls.enable", "true");
            p.put("mail.smtp.host", "smtp.gmail.com");
            p.put("mail.smtp.port", 587);
            String accountName = "thangtqps15783@fpt.edu.vn";
            String accountPassword = "0375273901";
            Session s = Session.getInstance(p,
                    new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(accountName, accountPassword);
                }
            });

            String from = "thangtqps15783@fpt.edu.vn";
            String to = t;
            String subject = "Mat Khau Moi Cua Ban La: ";
            Random random = new Random();
            int x = random.nextInt(10000);
            String noidung = String.valueOf(x);

            String body = noidung;
            Message msg = new MimeMessage(s);
            msg.setFrom(new InternetAddress(from));
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
            msg.setSubject(subject);
            msg.setText(body);
            Transport.send(msg);

            String sql = "update TaiKhoan set MatKhau = ? " + " where Email = ?";
            Connection conn = null;
            PreparedStatement ps = null;
            try {
                conn = DriverManager.getConnection(url);
                ps = conn.prepareStatement(sql);
                ps.setString(1, noidung);
                ps.setString(2, to);
                ps.execute();
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    if (conn != null) {
                        conn.close();
                    }

                    if (ps != null) {
                        ps.close();
                    }
                } catch (Exception e2) {
                    e2.printStackTrace();
                }
            }
            JOptionPane.showMessageDialog(null, "Mat Khau Da Duoc Gui Vao Email Cua Ban - Vui Long Kiem Tra Emai ", "Message",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (MessagingException ex) {
//                        Logger.getLogger(SendMail.class.getName()).log(Level.SEVERE, null, ex);
            MsgBox.alert(this, "Lỗi gửi Email ");
            ex.printStackTrace();
        }
    }
    
    void dangnhap(){
        String tendangnhap = txtTenDangNhap.getText();
        String matkhau = new String(txtMatKhau.getPassword());
        TaiKhoan taikhoan = dao.selectById(tendangnhap);
        if(tendangnhap.equals("")){
            MsgBox.alert(this,"Vui lòng nhập tài khoản ");
        }
        else if(taikhoan==null){
            MsgBox.alert(this,"Sai tên tài khoản");
        }else if(matkhau.equals("")){
            MsgBox.alert(this,"Vui lòng nhập mật khẩu ");
        }else if(!matkhau.equals(taikhoan.getMatKhau())){
            MsgBox.alert(this,"Mật khẩu sai ");
        }else if(matkhau.equals("")){
                MsgBox.alert(this,"Vui lòng nhập mật khẩu ");
        }else{
            Auth.user = taikhoan;
            MsgBox.alert(this, "đăng nhập thành công ");
            if(Auth.isStudent()){
                Frame frame = new MainJFrame_SV();
                frame.setVisible(true);
            }else{
                Frame frame1 = new MainJFrame_GV_CBDT();
                frame1.setVisible(true);
            }
            this.dispose();
        }    
    }

}
