/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.ui;

import com.poly.utils.MsgBox;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author admin
 */
public class MainJFrame_SV extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame_SV() {
        initComponents();
        init();
        chuChay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNen = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblHoSo = new javax.swing.JLabel();
        lblHuongdan = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tblMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlQLSV = new javax.swing.JPanel();
        lblTraCuuDiem = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlQLL = new javax.swing.JPanel();
        lblDangKyThiLai = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlDMK = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblDoiMatKhau = new javax.swing.JLabel();
        pnlThoat = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblThoat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlThongTin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblThongTin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNen.setBackground(new java.awt.Color(255, 255, 255));
        pnlNen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblHoSo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/account-circle.png"))); // NOI18N

        lblHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/alarm-light-outline.png"))); // NOI18N
        lblHuongdan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHuongdanMouseClicked(evt);
            }
        });

        lblDongHo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/alarm.png"))); // NOI18N

        lblText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblText.setForeground(new java.awt.Color(255, 51, 51));
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("Đừng bao giờ ngừng học tập vì cuộc đời không bao giờ ngừng dạy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblHuongdan)
                .addGap(18, 18, 18)
                .addComponent(lblHoSo)
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHoSo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(lblHuongdan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDongHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlNenLayout = new javax.swing.GroupLayout(pnlNen);
        pnlNen.setLayout(pnlNenLayout);
        pnlNenLayout.setHorizontalGroup(
            pnlNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tblMain)
        );
        pnlNenLayout.setVerticalGroup(
            pnlNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNenLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblMain, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 0, 670, 640));

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHome.setBackground(new java.awt.Color(32, 33, 35));
        pnlHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHomeMouseExited(evt);
            }
        });

        lblHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setText("Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/home-account.png"))); // NOI18N

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        jPanel1.add(pnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, -1, 40));

        pnlQLSV.setBackground(new java.awt.Color(32, 33, 35));
        pnlQLSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlQLSVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQLSVMouseExited(evt);
            }
        });
        pnlQLSV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTraCuuDiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTraCuuDiem.setForeground(new java.awt.Color(255, 255, 255));
        lblTraCuuDiem.setText("Tra Cứu Điểm");
        lblTraCuuDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTraCuuDiemMouseClicked(evt);
            }
        });
        pnlQLSV.add(lblTraCuuDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2, 160, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/flower-tulip.png"))); // NOI18N
        pnlQLSV.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jPanel1.add(pnlQLSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 40));

        pnlQLL.setBackground(new java.awt.Color(32, 33, 35));
        pnlQLL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlQLLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQLLMouseExited(evt);
            }
        });
        pnlQLL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDangKyThiLai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDangKyThiLai.setForeground(new java.awt.Color(255, 255, 255));
        lblDangKyThiLai.setText("Đăng Ký Thi Lại");
        lblDangKyThiLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangKyThiLaiMouseClicked(evt);
            }
        });
        pnlQLL.add(lblDangKyThiLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 160, 21));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/google-downasaur.png"))); // NOI18N
        pnlQLL.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(pnlQLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, -1));

        pnlDMK.setBackground(new java.awt.Color(32, 33, 35));
        pnlDMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDMKMouseExited(evt);
            }
        });
        pnlDMK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/all-inclusive-box.png"))); // NOI18N
        pnlDMK.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        lblDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblDoiMatKhau.setText("Đổi Mật Khẩu");
        lblDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoiMatKhauMouseClicked(evt);
            }
        });
        pnlDMK.add(lblDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 137, -1));

        jPanel1.add(pnlDMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 210, 50));

        pnlThoat.setBackground(new java.awt.Color(32, 33, 35));
        pnlThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThoatMouseExited(evt);
            }
        });
        pnlThoat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/power.png"))); // NOI18N
        pnlThoat.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(255, 255, 255));
        lblThoat.setText("Thoát");
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        pnlThoat.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 160, -1));

        jPanel1.add(pnlThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/img/Capture.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 50));

        pnlThongTin.setBackground(new java.awt.Color(32, 33, 35));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/baby-face.png"))); // NOI18N

        lblThongTin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThongTin.setForeground(new java.awt.Color(255, 255, 255));
        lblThongTin.setText("Thông Tin Chuyển Khoản");
        lblThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongTinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(lblThongTin)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(pnlThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblThoatMouseClicked

    private void lblDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMatKhauMouseClicked

        doimatkhau = new DoiMatKhau();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/all-inclusive-box.png"));
        tblMain.addTab("Đổi Mật Khẩu", icon, doimatkhau, "Đổi Mật Khẩu");

        tblMain.setSelectedComponent(doimatkhau);
    }//GEN-LAST:event_lblDoiMatKhauMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        tblMain.removeAll();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblTraCuuDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTraCuuDiemMouseClicked
        diemthi = new TraCuuDiemThi();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/flower-tulip (1).png"));
        tblMain.addTab("Tra Cứu Điểm Thi", icon, diemthi, "Tra Cứu Điểm Thi");

        tblMain.setSelectedComponent(diemthi);
    }//GEN-LAST:event_lblTraCuuDiemMouseClicked

    private void lblDangKyThiLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangKyThiLaiMouseClicked
        thilai = new DangKyThiLaiPN();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/google-downasaur (1).png"));
        tblMain.addTab("Đăng Ký Thi Lại", icon, thilai, "Đăng Ký Thi Lại");

        tblMain.setSelectedComponent(thilai);
    }//GEN-LAST:event_lblDangKyThiLaiMouseClicked

    private void pnlHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseEntered
        pnlHome.setBackground(new Color(102, 255, 204));
        lblHome.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlHomeMouseEntered

    private void pnlHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseExited
        pnlHome.setBackground(new Color(32, 33, 35));
        lblHome.setForeground(Color.white);
    }//GEN-LAST:event_pnlHomeMouseExited

    private void pnlQLSVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLSVMouseEntered
        pnlQLSV.setBackground(new Color(102, 255, 204));
        lblTraCuuDiem.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlQLSVMouseEntered

    private void pnlQLSVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLSVMouseExited
        pnlQLSV.setBackground(new Color(32, 33, 35));
        lblTraCuuDiem.setForeground(Color.white);
    }//GEN-LAST:event_pnlQLSVMouseExited

    private void pnlQLLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLLMouseEntered
        pnlQLL.setBackground(new Color(102, 255, 204));
        lblDangKyThiLai.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlQLLMouseEntered

    private void pnlQLLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLLMouseExited
        pnlQLL.setBackground(new Color(32, 33, 35));
        lblDangKyThiLai.setForeground(Color.white);
    }//GEN-LAST:event_pnlQLLMouseExited

    private void pnlDMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDMKMouseEntered
        pnlDMK.setBackground(new Color(102, 255, 204));
        lblDoiMatKhau.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlDMKMouseEntered

    private void pnlDMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDMKMouseExited
        pnlDMK.setBackground(new Color(32, 33, 35));
        lblDoiMatKhau.setForeground(Color.white);
    }//GEN-LAST:event_pnlDMKMouseExited

    private void pnlThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThoatMouseEntered
        pnlThoat.setBackground(new Color(102, 255, 204));
        lblThoat.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlThoatMouseEntered

    private void pnlThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThoatMouseExited
        pnlThoat.setBackground(new Color(32, 33, 35));
        lblThoat.setForeground(Color.white);
    }//GEN-LAST:event_pnlThoatMouseExited

    private void lblThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongTinMouseClicked
        chuyenkhoan = new ThongTinCK();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/baby-face (1).png"));
        tblMain.addTab("Thông Tin Chuyển Khoản", icon, chuyenkhoan, "Thông Tin Chuyển Khoản");

        tblMain.setSelectedComponent(chuyenkhoan);
    }//GEN-LAST:event_lblThongTinMouseClicked

    private void lblHuongdanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuongdanMouseClicked
       this.openHuongDan();
    }//GEN-LAST:event_lblHuongdanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_SV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_SV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_SV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_SV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame_SV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDangKyThiLai;
    private javax.swing.JLabel lblDoiMatKhau;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblHoSo;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHuongdan;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblThongTin;
    private javax.swing.JLabel lblTraCuuDiem;
    private javax.swing.JPanel pnlDMK;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlNen;
    private javax.swing.JPanel pnlQLL;
    private javax.swing.JPanel pnlQLSV;
    private javax.swing.JPanel pnlThoat;
    private javax.swing.JPanel pnlThongTin;
    private javax.swing.JTabbedPane tblMain;
    // End of variables declaration//GEN-END:variables

    private TraCuuDiemThi diemthi;
    private DangKyThiLaiPN thilai;
    private DoiMatKhau doimatkhau;
    private ThongTinCK chuyenkhoan;

    private void init() {
        this.setLocationRelativeTo(null);

//        new ChaoJDialog(this, true).setVisible(true);
//        new DangNhapJDialog(this, true).setVisible(true);
        new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                String text = formater.format(now);
                lblDongHo.setText(text);
            }
        }).start();
    }

    public void chuChay() {
        Thread thread1 = new Thread() {
            @Override
            public void run() {
                String txt = lblText.getText() + "       ";
                while (true) {
                    txt = txt.substring(1, txt.length()) + txt.charAt(0);
//                      txt = txt.charAt(txt.length() -1) +   txt.substring(0, txt.length() - 1);
                    try {
                        sleep(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainJFrame_SV.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    lblText.setText(txt);
                }
            }

        };
        thread1.start();
    }

    void openHuongDan() {
        try {
            Desktop.getDesktop().browse(new File("src\\main\\java\\com\\poly\\help\\index.html").toURI());
        } catch (IOException e) {
            MsgBox.alert(this, "Không tìm thấy file hướng dẫn");
        }
    }
}
