/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.ui;

import com.poly.utils.MsgBox;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author admin
 */
public class MainJFrame_GV_CBDT extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame_GV_CBDT() {
        initComponents();
        init();
        chuChay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNen = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblHoSo = new javax.swing.JLabel();
        lblTaoTaiKhoan = new javax.swing.JLabel();
        lblHuongdan = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tblMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlQLSV = new javax.swing.JPanel();
        lblQLSinhVien = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlQLL = new javax.swing.JPanel();
        lblQLLop = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlQLMH = new javax.swing.JPanel();
        lblQLMonHoc = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlQLK = new javax.swing.JPanel();
        lblQLKhoa = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlQLGV = new javax.swing.JPanel();
        lblQLGiangVien = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnlQLD = new javax.swing.JPanel();
        lblQLDiemSV = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pnlQLTK = new javax.swing.JPanel();
        lblQLThongKe = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlDMK = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblDoiMatKhau = new javax.swing.JLabel();
        pnlThoat = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblThoat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlDSTL = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblDSTL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNen.setBackground(new java.awt.Color(255, 255, 255));
        pnlNen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblHoSo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/account-circle.png"))); // NOI18N

        lblTaoTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/account-lock-open.png"))); // NOI18N
        lblTaoTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTaoTaiKhoanMouseClicked(evt);
            }
        });

        lblHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/alarm-light-outline.png"))); // NOI18N
        lblHuongdan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHuongdanMouseClicked(evt);
            }
        });

        lblDongHo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/alarm.png"))); // NOI18N

        lblText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblText.setForeground(new java.awt.Color(255, 51, 51));
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("Đừng bao giờ ngừng học tập vì cuộc đời không bao giờ ngừng dạy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHuongdan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTaoTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHoSo)
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHoSo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(lblTaoTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHuongdan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDongHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlNenLayout = new javax.swing.GroupLayout(pnlNen);
        pnlNen.setLayout(pnlNenLayout);
        pnlNenLayout.setHorizontalGroup(
            pnlNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tblMain)
        );
        pnlNenLayout.setVerticalGroup(
            pnlNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNenLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblMain, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 0, 670, 640));

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHome.setBackground(new java.awt.Color(32, 33, 35));
        pnlHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHomeMouseExited(evt);
            }
        });

        lblHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setText("Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/home-account.png"))); // NOI18N

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        jPanel1.add(pnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, -1, 40));

        pnlQLSV.setBackground(new java.awt.Color(32, 33, 35));
        pnlQLSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlQLSVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQLSVMouseExited(evt);
            }
        });
        pnlQLSV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLSinhVien.setForeground(new java.awt.Color(255, 255, 255));
        lblQLSinhVien.setText("Quản Lí Sinh Viên");
        lblQLSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLSinhVienMouseClicked(evt);
            }
        });
        pnlQLSV.add(lblQLSinhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2, 160, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/account-edit.png"))); // NOI18N
        pnlQLSV.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 30, 30));

        jPanel1.add(pnlQLSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 40));

        pnlQLL.setBackground(new java.awt.Color(32, 33, 35));
        pnlQLL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlQLLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQLLMouseExited(evt);
            }
        });
        pnlQLL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLLop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLLop.setForeground(new java.awt.Color(255, 255, 255));
        lblQLLop.setText("Quản Lí Lớp");
        lblQLLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLLopMouseClicked(evt);
            }
        });
        pnlQLL.add(lblQLLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 160, 21));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/google-classroom.png"))); // NOI18N
        pnlQLL.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(pnlQLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 40));

        pnlQLMH.setBackground(new java.awt.Color(32, 33, 35));
        pnlQLMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlQLMHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQLMHMouseExited(evt);
            }
        });
        pnlQLMH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLMonHoc.setForeground(new java.awt.Color(255, 255, 255));
        lblQLMonHoc.setText("Quản Lí Môn Học");
        lblQLMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLMonHocMouseClicked(evt);
            }
        });
        pnlQLMH.add(lblQLMonHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 160, 21));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/application-edit.png"))); // NOI18N
        pnlQLMH.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(pnlQLMH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 40));

        pnlQLK.setBackground(new java.awt.Color(32, 33, 35));
        pnlQLK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlQLKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQLKMouseExited(evt);
            }
        });
        pnlQLK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLKhoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLKhoa.setForeground(new java.awt.Color(255, 255, 255));
        lblQLKhoa.setText("Quản Lí Khoa");
        lblQLKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLKhoaMouseClicked(evt);
            }
        });
        pnlQLK.add(lblQLKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 160, 21));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/book-education-outline.png"))); // NOI18N
        pnlQLK.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(pnlQLK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 210, 40));

        pnlQLGV.setBackground(new java.awt.Color(32, 33, 35));
        pnlQLGV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlQLGVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQLGVMouseExited(evt);
            }
        });
        pnlQLGV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLGiangVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLGiangVien.setForeground(new java.awt.Color(255, 255, 255));
        lblQLGiangVien.setText("Quản Lí Giảng Viên");
        lblQLGiangVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLGiangVienMouseClicked(evt);
            }
        });
        pnlQLGV.add(lblQLGiangVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 164, 21));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/camera-control.png"))); // NOI18N
        pnlQLGV.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(pnlQLGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 40));

        pnlQLD.setBackground(new java.awt.Color(32, 33, 35));
        pnlQLD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlQLDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQLDMouseExited(evt);
            }
        });
        pnlQLD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLDiemSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLDiemSV.setForeground(new java.awt.Color(255, 255, 255));
        lblQLDiemSV.setText("Quản Lí Điểm ");
        lblQLDiemSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLDiemSVMouseClicked(evt);
            }
        });
        pnlQLD.add(lblQLDiemSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 164, 21));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/crown-outline.png"))); // NOI18N
        pnlQLD.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(pnlQLD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, 40));

        pnlQLTK.setBackground(new java.awt.Color(32, 33, 35));
        pnlQLTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlQLTKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQLTKMouseExited(evt);
            }
        });
        pnlQLTK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLThongKe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lblQLThongKe.setText("Quản Lí Thống Kê");
        lblQLThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLThongKeMouseClicked(evt);
            }
        });
        pnlQLTK.add(lblQLThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 164, 21));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/database-arrow-up.png"))); // NOI18N
        pnlQLTK.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(pnlQLTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 210, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, -1));

        pnlDMK.setBackground(new java.awt.Color(32, 33, 35));
        pnlDMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDMKMouseExited(evt);
            }
        });
        pnlDMK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/all-inclusive-box.png"))); // NOI18N
        pnlDMK.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        lblDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblDoiMatKhau.setText("Đổi Mật Khẩu");
        lblDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoiMatKhauMouseClicked(evt);
            }
        });
        pnlDMK.add(lblDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 137, -1));

        jPanel1.add(pnlDMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 210, 50));

        pnlThoat.setBackground(new java.awt.Color(32, 33, 35));
        pnlThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThoatMouseExited(evt);
            }
        });
        pnlThoat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/power.png"))); // NOI18N
        pnlThoat.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(255, 255, 255));
        lblThoat.setText("Thoát");
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        pnlThoat.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 160, -1));

        jPanel1.add(pnlThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/img/Capture.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 50));

        pnlDSTL.setBackground(new java.awt.Color(32, 33, 35));
        pnlDSTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDSTLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDSTLMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/account-reactivate-outline.png"))); // NOI18N

        lblDSTL.setBackground(new java.awt.Color(255, 255, 255));
        lblDSTL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDSTL.setForeground(new java.awt.Color(255, 255, 255));
        lblDSTL.setText("Danh Sách Thi Lại");
        lblDSTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDSTLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDSTLLayout = new javax.swing.GroupLayout(pnlDSTL);
        pnlDSTL.setLayout(pnlDSTLLayout);
        pnlDSTLLayout.setHorizontalGroup(
            pnlDSTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDSTLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDSTL, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        pnlDSTLLayout.setVerticalGroup(
            pnlDSTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDSTLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDSTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDSTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(pnlDSTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTaoTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaoTaiKhoanMouseClicked

        taotaikhoan = new TaoTaiKhoan();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/account-lock-open.png"));
        tblMain.addTab("Tạo Tài Khoản", icon, taotaikhoan, "Tạo Tài Khoản");

        tblMain.setSelectedComponent(taotaikhoan);


    }//GEN-LAST:event_lblTaoTaiKhoanMouseClicked

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblThoatMouseClicked

    private void lblDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMatKhauMouseClicked

        doimatkhau = new DoiMatKhau();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/all-inclusive-box.png"));
        tblMain.addTab("Đổi Mật Khẩu", icon, doimatkhau, "Đổi Mật Khẩu");

        tblMain.setSelectedComponent(doimatkhau);
    }//GEN-LAST:event_lblDoiMatKhauMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        tblMain.removeAll();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblQLSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLSinhVienMouseClicked
        qlsinhvien = new SinhVienPN();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/9.png"));
        tblMain.addTab("Quản Lí Sinh Viên", icon, qlsinhvien, "Quản Lí Sinh Viên");

        tblMain.setSelectedComponent(qlsinhvien);
    }//GEN-LAST:event_lblQLSinhVienMouseClicked

    private void lblQLGiangVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLGiangVienMouseClicked
        qlgiangvien = new GiangVienPN();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/3.png"));
        tblMain.addTab("Quản Giảng Viên", icon, qlgiangvien, "Quản Lí Giảng Viên");

        tblMain.setSelectedComponent(qlgiangvien);
    }//GEN-LAST:event_lblQLGiangVienMouseClicked

    private void lblQLDiemSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLDiemSVMouseClicked
        qldiemsinhvien = new DiemSinhVien();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/2.png"));
        tblMain.addTab("Thông Tin Điểm Sinh Viên", icon, qldiemsinhvien, "Thông Tin Điểm Sinh Viên");

        tblMain.setSelectedComponent(qldiemsinhvien);
    }//GEN-LAST:event_lblQLDiemSVMouseClicked

    private void lblQLLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLLopMouseClicked
        qllop = new LopPN();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/1.png"));
        tblMain.addTab("Quản Lí Lớp", icon, qllop, "Quản Lí Lớp");

        tblMain.setSelectedComponent(qllop);
    }//GEN-LAST:event_lblQLLopMouseClicked

    private void lblQLKhoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLKhoaMouseClicked
        qlkhoa = new KhoaPN();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/4.png"));
        tblMain.addTab("Quản Lí Khoa", icon, qlkhoa, "Quản Lí Khoa");

        tblMain.setSelectedComponent(qlkhoa);
    }//GEN-LAST:event_lblQLKhoaMouseClicked

    private void lblQLMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLMonHocMouseClicked
        qlmonhoc = new MonHocPN();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/7.png"));
        tblMain.addTab("Quản Lí Môn Học", icon, qlmonhoc, "Quản Lí Môn Học");

        tblMain.setSelectedComponent(qlmonhoc);
    }//GEN-LAST:event_lblQLMonHocMouseClicked

    private void pnlHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseEntered
        pnlHome.setBackground(new Color(102, 255, 204));
        lblHome.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlHomeMouseEntered

    private void pnlHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHomeMouseExited
        pnlHome.setBackground(new Color(32, 33, 35));
        lblHome.setForeground(Color.white);
    }//GEN-LAST:event_pnlHomeMouseExited

    private void pnlQLSVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLSVMouseEntered
        pnlQLSV.setBackground(new Color(102, 255, 204));
        lblQLSinhVien.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlQLSVMouseEntered

    private void pnlQLSVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLSVMouseExited
        pnlQLSV.setBackground(new Color(32, 33, 35));
        lblQLSinhVien.setForeground(Color.white);
    }//GEN-LAST:event_pnlQLSVMouseExited

    private void pnlQLLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLLMouseEntered
        pnlQLL.setBackground(new Color(102, 255, 204));
        lblQLLop.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlQLLMouseEntered

    private void pnlQLLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLLMouseExited
        pnlQLL.setBackground(new Color(32, 33, 35));
        lblQLLop.setForeground(Color.white);
    }//GEN-LAST:event_pnlQLLMouseExited

    private void pnlQLMHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLMHMouseEntered
        pnlQLMH.setBackground(new Color(102, 255, 204));
        lblQLMonHoc.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlQLMHMouseEntered

    private void pnlQLMHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLMHMouseExited
        pnlQLMH.setBackground(new Color(32, 33, 35));
        lblQLMonHoc.setForeground(Color.white);
    }//GEN-LAST:event_pnlQLMHMouseExited

    private void pnlQLKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLKMouseEntered
        pnlQLK.setBackground(new Color(102, 255, 204));
        lblQLKhoa.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlQLKMouseEntered

    private void pnlQLKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLKMouseExited
        pnlQLK.setBackground(new Color(32, 33, 35));
        lblQLKhoa.setForeground(Color.white);
    }//GEN-LAST:event_pnlQLKMouseExited

    private void pnlQLGVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLGVMouseEntered
        pnlQLGV.setBackground(new Color(102, 255, 204));
        lblQLGiangVien.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlQLGVMouseEntered

    private void pnlQLGVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLGVMouseExited
        pnlQLGV.setBackground(new Color(32, 33, 35));
        lblQLGiangVien.setForeground(Color.white);
    }//GEN-LAST:event_pnlQLGVMouseExited

    private void pnlQLDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLDMouseEntered
        pnlQLD.setBackground(new Color(102, 255, 204));
        lblQLDiemSV.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlQLDMouseEntered

    private void pnlQLDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLDMouseExited
        pnlQLD.setBackground(new Color(32, 33, 35));
        lblQLDiemSV.setForeground(Color.white);
    }//GEN-LAST:event_pnlQLDMouseExited

    private void pnlQLTKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLTKMouseEntered
        pnlQLTK.setBackground(new Color(102, 255, 204));
        lblQLThongKe.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlQLTKMouseEntered

    private void pnlQLTKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQLTKMouseExited
        pnlQLTK.setBackground(new Color(32, 33, 35));
        lblQLThongKe.setForeground(Color.white);
    }//GEN-LAST:event_pnlQLTKMouseExited

    private void pnlDMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDMKMouseEntered
        pnlDMK.setBackground(new Color(102, 255, 204));
        lblDoiMatKhau.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlDMKMouseEntered

    private void pnlDMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDMKMouseExited
        pnlDMK.setBackground(new Color(32, 33, 35));
        lblDoiMatKhau.setForeground(Color.white);
    }//GEN-LAST:event_pnlDMKMouseExited

    private void pnlThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThoatMouseEntered
        pnlThoat.setBackground(new Color(102, 255, 204));
        lblThoat.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlThoatMouseEntered

    private void pnlThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThoatMouseExited
        pnlThoat.setBackground(new Color(32, 33, 35));
        lblThoat.setForeground(Color.white);
    }//GEN-LAST:event_pnlThoatMouseExited

    private void lblQLThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLThongKeMouseClicked
        thongke = new ThongKePN();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/10.png"));
        tblMain.addTab("Thống Kê", icon, thongke, "Thống Kê");

        tblMain.setSelectedComponent(thongke);
    }//GEN-LAST:event_lblQLThongKeMouseClicked

    private void lblDSTLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDSTLMouseClicked
        dsdktl = new DSDangKyThiLai();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/account-reactivate-outline (1).png"));
        tblMain.addTab("Danh Sách Đăng Ký Thi Lại", icon, dsdktl, "Danh Sách Đăng Ký Thi Lại");

        tblMain.setSelectedComponent(dsdktl);
    }//GEN-LAST:event_lblDSTLMouseClicked

    private void pnlDSTLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDSTLMouseEntered
        pnlDSTL.setBackground(new Color(102, 255, 204));
        lblDSTL.setForeground(new Color(32, 33, 35));
    }//GEN-LAST:event_pnlDSTLMouseEntered

    private void pnlDSTLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDSTLMouseExited
        pnlDSTL.setBackground(new Color(32, 33, 35));
        lblDSTL.setForeground(Color.white);
    }//GEN-LAST:event_pnlDSTLMouseExited

    private void lblHuongdanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuongdanMouseClicked
        this.openHuongDan();
    }//GEN-LAST:event_lblHuongdanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_GV_CBDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_GV_CBDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_GV_CBDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame_GV_CBDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame_GV_CBDT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDSTL;
    private javax.swing.JLabel lblDoiMatKhau;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblHoSo;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHuongdan;
    private javax.swing.JLabel lblQLDiemSV;
    private javax.swing.JLabel lblQLGiangVien;
    private javax.swing.JLabel lblQLKhoa;
    private javax.swing.JLabel lblQLLop;
    private javax.swing.JLabel lblQLMonHoc;
    private javax.swing.JLabel lblQLSinhVien;
    private javax.swing.JLabel lblQLThongKe;
    private javax.swing.JLabel lblTaoTaiKhoan;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JPanel pnlDMK;
    private javax.swing.JPanel pnlDSTL;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlNen;
    private javax.swing.JPanel pnlQLD;
    private javax.swing.JPanel pnlQLGV;
    private javax.swing.JPanel pnlQLK;
    private javax.swing.JPanel pnlQLL;
    private javax.swing.JPanel pnlQLMH;
    private javax.swing.JPanel pnlQLSV;
    private javax.swing.JPanel pnlQLTK;
    private javax.swing.JPanel pnlThoat;
    private javax.swing.JTabbedPane tblMain;
    // End of variables declaration//GEN-END:variables

    private TaoTaiKhoan taotaikhoan;
    private DoiMatKhau doimatkhau;
    private SinhVienPN qlsinhvien;
    private GiangVienPN qlgiangvien;
    private DiemSinhVien qldiemsinhvien;
    private LopPN qllop;
    private KhoaPN qlkhoa;
    private MonHocPN qlmonhoc;
    private ThongKePN thongke;
    private DSDangKyThiLai dsdktl;

    private void init() {
        this.setLocationRelativeTo(null);

//        new ChaoJDialog(this, true).setVisible(true);
//        new DangNhapJDialog(this, true).setVisible(true);
        new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                String text = formater.format(now);
                lblDongHo.setText(text);
            }
        }).start();
    }

    public void chuChay() {
        Thread thread1 = new Thread() {
            @Override
            public void run() {
                String txt = lblText.getText() + "       ";
                while (true) {
                    txt = txt.substring(1, txt.length()) + txt.charAt(0);
//                      txt = txt.charAt(txt.length() -1) +   txt.substring(0, txt.length() - 1);
                    try {
                        sleep(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainJFrame_GV_CBDT.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    lblText.setText(txt);
                }
            }

        };
        thread1.start();
    }

    void openHuongDan() {
        try {
            Desktop.getDesktop().browse(new File("src\\main\\java\\com\\poly\\help\\index.html").toURI());
        } catch (IOException e) {
            MsgBox.alert(this, "Không tìm thấy file hướng dẫn");
        }
    }
}
