/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.ui;

import com.poly.dao.KhoaDAO;
import com.poly.dao.LopDAO;
import com.poly.dao.ThongKeDAO;
import com.poly.entity.Khoa;
import com.poly.entity.Lop;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ThongKePN extends javax.swing.JPanel {

    /**
     * Creates new form ThongKePN
     */
    public ThongKePN() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cboKhoa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSLop = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboLop = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSSinhVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbokhoa2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbolop2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTop = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblKGioi = new javax.swing.JLabel();
        lblKKha = new javax.swing.JLabel();
        lblKTB = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lblKYeu = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblLGioi = new javax.swing.JLabel();
        lblLKha = new javax.swing.JLabel();
        lblLTB = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        lblLYeu = new javax.swing.JLabel();

        tabs.setBackground(new java.awt.Color(255, 255, 255));
        tabs.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cboKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhoaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Khoa:");

        tblDSLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Khoa", "Năm Thành Lập", "Mã Lớp", "Tên Lớp"
            }
        ));
        jScrollPane1.setViewportView(tblDSLop);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboKhoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Lớp", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Lớp: ");

        cboLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLopActionPerformed(evt);
            }
        });

        tblDSSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên Lớp", "Mã Sinh Viên", "Họ Tên ", "Ngày Sinh", "Giới Tính"
            }
        ));
        jScrollPane2.setViewportView(tblDSSinhVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboLop, 0, 573, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Sinh Viên", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Khoa:");

        cbokhoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbokhoa2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Lop:");

        cbolop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbolop2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Top 5 Sinh Viên Có Điểm Cao Nhất:");

        tblTop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hạng", "Mã Sinh Viên", "Tên Sinh Viên", "Điểm TB", "Khoa"
            }
        ));
        jScrollPane3.setViewportView(tblTop);

        jPanel5.setBackground(new java.awt.Color(32, 33, 35));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(57, 113, 177));
        jLabel30.setText("Số SV Giỏi:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(57, 113, 177));
        jLabel31.setText("Số SV Khá:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(57, 113, 177));
        jLabel32.setText("Số SV TB:");

        lblKGioi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKGioi.setForeground(new java.awt.Color(102, 255, 204));
        lblKGioi.setText("0");

        lblKKha.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKKha.setForeground(new java.awt.Color(102, 255, 204));
        lblKKha.setText("0");

        lblKTB.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKTB.setForeground(new java.awt.Color(102, 255, 204));
        lblKTB.setText("0");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(57, 113, 177));
        jLabel40.setText("Số SV Yếu:");

        lblKYeu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblKYeu.setForeground(new java.awt.Color(102, 255, 204));
        lblKYeu.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKTB)
                    .addComponent(lblKGioi))
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKYeu)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKKha))
                .addGap(0, 71, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKGioi)
                    .addComponent(lblKKha))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKTB)
                    .addComponent(lblKYeu))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(32, 33, 35));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(57, 113, 177));
        jLabel42.setText("Số SV Giỏi:");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(57, 113, 177));
        jLabel43.setText("Số SV Khá:");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(57, 113, 177));
        jLabel44.setText("Số SV TB:");

        lblLGioi.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblLGioi.setForeground(new java.awt.Color(102, 255, 204));
        lblLGioi.setText("0");

        lblLKha.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblLKha.setForeground(new java.awt.Color(102, 255, 204));
        lblLKha.setText("0");

        lblLTB.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblLTB.setForeground(new java.awt.Color(102, 255, 204));
        lblLTB.setText("0");

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(57, 113, 177));
        jLabel52.setText("Số SV Yếu:");

        lblLYeu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblLYeu.setForeground(new java.awt.Color(102, 255, 204));
        lblLYeu.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLGioi)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLTB))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLYeu)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLKha))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLGioi)
                    .addComponent(lblLKha))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLTB)
                    .addComponent(lblLYeu))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbokhoa2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cbolop2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbokhoa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbolop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Thống Kê Điểm", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoaActionPerformed
        this.fillTableLop();
    }//GEN-LAST:event_cboKhoaActionPerformed

    private void cboLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLopActionPerformed
        this.fillTableSinhVien();
    }//GEN-LAST:event_cboLopActionPerformed

    private void cbokhoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbokhoa2ActionPerformed
        this.fillTKDiemK();
        this.fillToTableTopSV();
        this.fillComboLop();
        this.fillTKDiemL();
    }//GEN-LAST:event_cbokhoa2ActionPerformed

    private void cbolop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbolop2ActionPerformed
        this.fillTKDiemL();
        this.fillToTableTopSV();
    }//GEN-LAST:event_cbolop2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboKhoa;
    private javax.swing.JComboBox<String> cboLop;
    private javax.swing.JComboBox<String> cbokhoa2;
    private javax.swing.JComboBox<String> cbolop2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblKGioi;
    private javax.swing.JLabel lblKKha;
    private javax.swing.JLabel lblKTB;
    private javax.swing.JLabel lblKYeu;
    private javax.swing.JLabel lblLGioi;
    private javax.swing.JLabel lblLKha;
    private javax.swing.JLabel lblLTB;
    private javax.swing.JLabel lblLYeu;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblDSLop;
    private javax.swing.JTable tblDSSinhVien;
    private javax.swing.JTable tblTop;
    // End of variables declaration//GEN-END:variables

    ThongKeDAO dao = new ThongKeDAO();
    KhoaDAO khdao = new KhoaDAO();
    LopDAO lopdao = new LopDAO();
    
    void init() {
        fillComboBoxKhoa();
        fillTableLop();
        fillComboBoxLop();
        fillTableSinhVien();
        
        this.fillComboBoxKhoaHoc();
        this.fillTKDiemK();
        this.fillToTableTopSV();
        this.fillComboLop();
        this.fillTKDiemL();
    }
    
    void fillComboBoxKhoa() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboKhoa.getModel();
        model.removeAllElements();
        List<Khoa> list = khdao.selectAll();
        for (Khoa kh : list) {
            model.addElement(kh);
        }
    }
    
    void fillTableLop() {
        DefaultTableModel model = (DefaultTableModel) tblDSLop.getModel();
        model.setRowCount(0);
        Khoa kh = (Khoa) cboKhoa.getSelectedItem();
        List<Object[]> list = dao.getLopTheoKhoa(kh.getMaKhoa());
        for (Object[] row : list) {
            model.addRow(row);
        }
    }
    
    void fillComboBoxLop() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLop.getModel();
        model.removeAllElements();
        List<Lop> list = lopdao.selectAll();
        for (Lop l : list) {
            model.addElement(l);
        }
    }
    
    void fillTableSinhVien() {
        DefaultTableModel model = (DefaultTableModel) tblDSSinhVien.getModel();
        model.setRowCount(0);
        Lop l = (Lop) cboLop.getSelectedItem();
        List<Object[]> list = dao.getSinhVienTheoLop(l.getMaLop());
        for (Object[] row : list) {
            model.addRow(row);
        }
    }
    
    //--------------------
    
    void fillComboBoxKhoaHoc(){
        DefaultComboBoxModel model =(DefaultComboBoxModel) cbokhoa2.getModel();
        model.removeAllElements();
        List<String> listK = dao.getKhoahoc();
        for(String kh : listK){
            model.addElement(kh);
        }
    }
    void fillTKDiemK(){
        int slkhaK=0;
        int slkemK=0;
        int slTBK=0;
        int slgioiK=0;
        String kh = (String) cbokhoa2.getSelectedItem();
        List<Double> ldiem = new ArrayList();
        if(kh!=null){
            List<Object[]> list = dao.getDiem(kh);
            for(Object[] row : list){
                Double diem = (Double)row[0];
                ldiem.add(diem);
            }
        }
            for(Double d : ldiem){
                
               if(d < 5){
                   slkemK++;
               }else if(d>=5 && d<=6.5){
                   slTBK++;
               }else if(d>6.5 && d<8){
                   slkhaK++;
               }else{
                   slgioiK++;
               }
            }
            double minK=0;
            double maxK=0;
            if(!ldiem.isEmpty()){
                maxK=ldiem.get(0);
                minK=ldiem.get(0);
                for(Double d : ldiem){
                    if(d<minK){
                        minK=d;
                    if(d>maxK){
                        maxK=d;
                    }
                }
            }
        }
        
        
        lblKGioi.setText(String.valueOf(slgioiK));
        lblKTB.setText(String.valueOf(slTBK));
        lblKYeu.setText(String.valueOf(slkemK));
        lblKKha.setText(String.valueOf(slkhaK));
//        lblKDiemCN.setText(String.valueOf(maxK));
//        lblKDiemTN.setText(String.valueOf(minK));
    }
    void fillToTableTopSV(){
        DefaultTableModel model2 =(DefaultTableModel)tblTop.getModel();
        model2.setRowCount(0);
        List<Object[]> list2 = dao.getBangDiem();
        for(Object[] row : list2){
            Double diem = (Double)row[3];
            model2.addRow(new Object[]{row[0],row[1],row[2],diem,row[4]});   
        }
        
    }
    void fillComboLop(){
        DefaultComboBoxModel model =(DefaultComboBoxModel)cbolop2.getModel();
        model.removeAllElements();
        String khoa = (String) cbokhoa2.getSelectedItem();
        if(khoa!=null){
            List<String> list = dao.getLop(khoa);
            for(String kh : list){
                model.addElement(kh);
            }
            this.fillTKDiemL();
        }
    }
    void fillTKDiemL(){
        int slkhaL=0;
        int slkemL=0;
        int slTBL=0;
        int slgioiL=0;
        String lop = (String) cbolop2.getSelectedItem();
        List<Double> lDiemL = new ArrayList();
        if(lop!=null){
        List<Object[]> list = dao.getDiemL(lop);
            for(Object[] row : list){
                Double diem = (Double)row[0];
                lDiemL.add(diem);
            }
        }
//            for(Double d : lDiemL){
//                
//               if(d<9 && d>=7.5 ){
//                   slkhaL++;
//               }else if(d<7.5 && d>=4.5){
//                   slTBL++;
//               }else if(d<4.5 && d>=0){
//                   slkemL++;
//               }else{
//                   slgioiL++;
//               }
//            }
            
            for(Double d : lDiemL){
                
               if(d < 5){
                   slkemL++;
               }else if(d>=5 && d<=6.5){
                   slTBL++;
               }else if(d>6.5 && d<8){
                   slkhaL++;
               }else{
                   slgioiL++;
               }
            }
            
            double minL=0;
            double maxL=0;
            if(!lDiemL.isEmpty()){
                maxL=lDiemL.get(0);
                minL=lDiemL.get(0);
                for(int i=0;i<lDiemL.size();i++){
                    if(lDiemL.get(i)<minL){
                        minL=lDiemL.get(i);
                    if(lDiemL.get(i)>maxL){
                        maxL=lDiemL.get(i);
                    }
                }
            }
              
        }
        
        
        lblLGioi.setText(String.valueOf(slgioiL));
        lblLYeu.setText(String.valueOf(slkemL));
        lblLTB.setText(String.valueOf(slTBL));
        lblLKha.setText(String.valueOf(slkhaL));
//        lblLDiemCN.setText(String.valueOf(maxL));
//        lblLDiemTN.setText(String.valueOf(minL));
    }
    
    
}

